### ISSUE TITLE
What Is the Rationale for Not Exporting Catlab?

### ISSUE THREAD

**Issue by TheCedarPrince** [AlgebraicJulia/Semagrams.jl#44]
Hi Semagrams team,

Great work on this! Just an initial thought and a suggestion on syntax:

Catlab seems to be a dependency of Semagrams - why not have Semagrams export functions from Catlab rather than making the user have to also write `using Catlab`? In the current Semagrams quickstart documentation section, it does not say that one has to also use Catlab.jl but for the tutorials to work, you do need it used. Doesn't seem like it would be an issue to re-export as it does not appear that Catlab overshadows or conflicts with Semagrams.

Only a suggestion for ease of use. Feel free to close!

~tcp

**Comment by TheCedarPrince** [comment]
I would imagine this re-exporting would also solve issues as I saw here: https://github.com/AlgebraicJulia/Semagrams.jl/issues/45

**Comment by jpfairbanks** [comment]
The module usage in Catlab is a little bit nonstandard in the julia community. We definitely tend to keep things in more isolation than would be typical in a julia package. Since most users so far are developers of Catlab, having the imports explicit hasn't been too much of a problem and we have some desire to break up Catlab into smaller packages where these imports would be from different packages rather than from Catlab. But we keep running into places where this use of modules is unexpected by new users, so we will need to come to a resolution one way or the other soon. 

I guess that semagrams could do the reexporting if it makes it easier on the users. @olynch, do you have any thoughts on it?

**Comment by olynch** [comment]
This issue is out of date as it refers to a different version of Semagrams.
